### PR TITLE
Created useful-resources.md

### PR DESCRIPTION
**Pull request by codedmachine111**
Added a few useful resources for junior developers. Issue #165 .

### CODE REVIEW

**Review by lasse-offerzen — CHANGES_REQUESTED** [review]
Hey @codedmachine111 I think the sidebar position number might be incorrect, try 12?

**Comment by codedmachine111** [comment]
Hello @lasse-offerzen . Updated the file by changing sidebar position to 12. Kindly review my PR.

**Comment by lasse-offerzen** [comment]
@codedmachine111 Still some issues it seems (see below):
Screenshot 2022-10-11 at 13 25 47

**Comment by codedmachine111** [comment]
Should I exclude the images or add them to the asset folder if they're giving the error or should I not use HTML tags in the markdown file. ?

**Comment by lasse-offerzen** [comment]
> 

@codedmachine111 I think both. So add images to the asset folder if they're giving the error and perhaps avoid HTML tags? 🙏

**Comment by codedmachine111** [comment]
Apologies. Will fix this as soon as possible.

**Pull request closed without merging**
